[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/create-portal-session"
  to = "/.netlify/functions/create-portal-session"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

